//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Возврат клиентом.
    /// </summary>
    // *** Start programmer edit section *** (ВозвратКлиентом CustomAttributes)

    // *** End programmer edit section *** (ВозвратКлиентом CustomAttributes)
    [AutoAltered()]
    [Caption("Возврат клиентом")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВозвратКлиентомE", new string[] {
            "ДатаПоступления as \'Дата поступления\'",
            "ДатаУстановки as \'Дата установки\'",
            "СерийныйНомер as \'Серийный номер\'",
            "ПричинаВозврата as \'Причина возврата\'",
            "Модель as \'Модель\'",
            "Модель.Название as \'Название\'",
            "Тип as \'Тип\'",
            "Тип.Название as \'Название\'",
            "Клиент as \'Клиент\'",
            "Клиент.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Модель.Название",
            "Тип.Название",
            "Клиент.ФИО"})]
    [MasterViewDefineAttribute("ВозвратКлиентомE", "Модель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ВозвратКлиентомE", "Тип", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ВозвратКлиентомE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class ВозвратКлиентом : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПоступления;
        
        private System.DateTime fДатаУстановки;
        
        private string fСерийныйНомер;
        
        private string fПричинаВозврата;
        
        private IIS.Kursovaya.Модель fМодель;
        
        private IIS.Kursovaya.Тип fТип;
        
        private IIS.Kursovaya.Клиент fКлиент;
        
        private IIS.Kursovaya.Филиал fФилиал;
        
        // *** Start programmer edit section *** (ВозвратКлиентом CustomMembers)

        // *** End programmer edit section *** (ВозвратКлиентом CustomMembers)

        
        /// <summary>
        /// ДатаПоступления.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратКлиентом.ДатаПоступления CustomAttributes)

        // *** End programmer edit section *** (ВозвратКлиентом.ДатаПоступления CustomAttributes)
        public virtual System.DateTime ДатаПоступления
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.ДатаПоступления Get start)

                // *** End programmer edit section *** (ВозвратКлиентом.ДатаПоступления Get start)
                System.DateTime result = this.fДатаПоступления;
                // *** Start programmer edit section *** (ВозвратКлиентом.ДатаПоступления Get end)

                // *** End programmer edit section *** (ВозвратКлиентом.ДатаПоступления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.ДатаПоступления Set start)

                // *** End programmer edit section *** (ВозвратКлиентом.ДатаПоступления Set start)
                this.fДатаПоступления = value;
                // *** Start programmer edit section *** (ВозвратКлиентом.ДатаПоступления Set end)

                // *** End programmer edit section *** (ВозвратКлиентом.ДатаПоступления Set end)
            }
        }
        
        /// <summary>
        /// ДатаУстановки.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратКлиентом.ДатаУстановки CustomAttributes)

        // *** End programmer edit section *** (ВозвратКлиентом.ДатаУстановки CustomAttributes)
        public virtual System.DateTime ДатаУстановки
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.ДатаУстановки Get start)

                // *** End programmer edit section *** (ВозвратКлиентом.ДатаУстановки Get start)
                System.DateTime result = this.fДатаУстановки;
                // *** Start programmer edit section *** (ВозвратКлиентом.ДатаУстановки Get end)

                // *** End programmer edit section *** (ВозвратКлиентом.ДатаУстановки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.ДатаУстановки Set start)

                // *** End programmer edit section *** (ВозвратКлиентом.ДатаУстановки Set start)
                this.fДатаУстановки = value;
                // *** Start programmer edit section *** (ВозвратКлиентом.ДатаУстановки Set end)

                // *** End programmer edit section *** (ВозвратКлиентом.ДатаУстановки Set end)
            }
        }
        
        /// <summary>
        /// ПричинаВозврата.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратКлиентом.ПричинаВозврата CustomAttributes)

        // *** End programmer edit section *** (ВозвратКлиентом.ПричинаВозврата CustomAttributes)
        [StrLen(255)]
        public virtual string ПричинаВозврата
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.ПричинаВозврата Get start)

                // *** End programmer edit section *** (ВозвратКлиентом.ПричинаВозврата Get start)
                string result = this.fПричинаВозврата;
                // *** Start programmer edit section *** (ВозвратКлиентом.ПричинаВозврата Get end)

                // *** End programmer edit section *** (ВозвратКлиентом.ПричинаВозврата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.ПричинаВозврата Set start)

                // *** End programmer edit section *** (ВозвратКлиентом.ПричинаВозврата Set start)
                this.fПричинаВозврата = value;
                // *** Start programmer edit section *** (ВозвратКлиентом.ПричинаВозврата Set end)

                // *** End programmer edit section *** (ВозвратКлиентом.ПричинаВозврата Set end)
            }
        }
        
        /// <summary>
        /// СерийныйНомер.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратКлиентом.СерийныйНомер CustomAttributes)

        // *** End programmer edit section *** (ВозвратКлиентом.СерийныйНомер CustomAttributes)
        [StrLen(255)]
        public virtual string СерийныйНомер
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.СерийныйНомер Get start)

                // *** End programmer edit section *** (ВозвратКлиентом.СерийныйНомер Get start)
                string result = this.fСерийныйНомер;
                // *** Start programmer edit section *** (ВозвратКлиентом.СерийныйНомер Get end)

                // *** End programmer edit section *** (ВозвратКлиентом.СерийныйНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.СерийныйНомер Set start)

                // *** End programmer edit section *** (ВозвратКлиентом.СерийныйНомер Set start)
                this.fСерийныйНомер = value;
                // *** Start programmer edit section *** (ВозвратКлиентом.СерийныйНомер Set end)

                // *** End programmer edit section *** (ВозвратКлиентом.СерийныйНомер Set end)
            }
        }
        
        /// <summary>
        /// Возврат клиентом.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратКлиентом.Клиент CustomAttributes)

        // *** End programmer edit section *** (ВозвратКлиентом.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Kursovaya.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.Клиент Get start)

                // *** End programmer edit section *** (ВозвратКлиентом.Клиент Get start)
                IIS.Kursovaya.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (ВозвратКлиентом.Клиент Get end)

                // *** End programmer edit section *** (ВозвратКлиентом.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.Клиент Set start)

                // *** End programmer edit section *** (ВозвратКлиентом.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (ВозвратКлиентом.Клиент Set end)

                // *** End programmer edit section *** (ВозвратКлиентом.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Возврат клиентом.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратКлиентом.Модель CustomAttributes)

        // *** End programmer edit section *** (ВозвратКлиентом.Модель CustomAttributes)
        [PropertyStorage(new string[] {
                "Модель"})]
        [NotNull()]
        public virtual IIS.Kursovaya.Модель Модель
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.Модель Get start)

                // *** End programmer edit section *** (ВозвратКлиентом.Модель Get start)
                IIS.Kursovaya.Модель result = this.fМодель;
                // *** Start programmer edit section *** (ВозвратКлиентом.Модель Get end)

                // *** End programmer edit section *** (ВозвратКлиентом.Модель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.Модель Set start)

                // *** End programmer edit section *** (ВозвратКлиентом.Модель Set start)
                this.fМодель = value;
                // *** Start programmer edit section *** (ВозвратКлиентом.Модель Set end)

                // *** End programmer edit section *** (ВозвратКлиентом.Модель Set end)
            }
        }
        
        /// <summary>
        /// Возврат клиентом.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратКлиентом.Тип CustomAttributes)

        // *** End programmer edit section *** (ВозвратКлиентом.Тип CustomAttributes)
        [PropertyStorage(new string[] {
                "Тип"})]
        [NotNull()]
        public virtual IIS.Kursovaya.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.Тип Get start)

                // *** End programmer edit section *** (ВозвратКлиентом.Тип Get start)
                IIS.Kursovaya.Тип result = this.fТип;
                // *** Start programmer edit section *** (ВозвратКлиентом.Тип Get end)

                // *** End programmer edit section *** (ВозвратКлиентом.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.Тип Set start)

                // *** End programmer edit section *** (ВозвратКлиентом.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (ВозвратКлиентом.Тип Set end)

                // *** End programmer edit section *** (ВозвратКлиентом.Тип Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya.Филиал.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратКлиентом.Филиал CustomAttributes)

        // *** End programmer edit section *** (ВозвратКлиентом.Филиал CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Филиал"})]
        public virtual IIS.Kursovaya.Филиал Филиал
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.Филиал Get start)

                // *** End programmer edit section *** (ВозвратКлиентом.Филиал Get start)
                IIS.Kursovaya.Филиал result = this.fФилиал;
                // *** Start programmer edit section *** (ВозвратКлиентом.Филиал Get end)

                // *** End programmer edit section *** (ВозвратКлиентом.Филиал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратКлиентом.Филиал Set start)

                // *** End programmer edit section *** (ВозвратКлиентом.Филиал Set start)
                this.fФилиал = value;
                // *** Start programmer edit section *** (ВозвратКлиентом.Филиал Set end)

                // *** End programmer edit section *** (ВозвратКлиентом.Филиал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВозвратКлиентомE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВозвратКлиентомE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВозвратКлиентомE", typeof(IIS.Kursovaya.ВозвратКлиентом));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ВозвратКлиентом.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfВозвратКлиентом CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfВозвратКлиентом CustomAttributes)
    public class DetailArrayOfВозвратКлиентом : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya.DetailArrayOfВозвратКлиентом members)

        // *** End programmer edit section *** (IIS.Kursovaya.DetailArrayOfВозвратКлиентом members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ВозвратКлиентом by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ВозвратКлиентом.
        /// </summary>
        public DetailArrayOfВозвратКлиентом(IIS.Kursovaya.Филиал fФилиал) : 
                base(typeof(ВозвратКлиентом), ((ICSSoft.STORMNET.DataObject)(fФилиал)))
        {
        }
        
        public IIS.Kursovaya.ВозвратКлиентом this[int index]
        {
            get
            {
                return ((IIS.Kursovaya.ВозвратКлиентом)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya.ВозвратКлиентом dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
