//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Модель.
    /// </summary>
    // *** Start programmer edit section *** (Модель CustomAttributes)

    // *** End programmer edit section *** (Модель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МодельE", new string[] {
            "Название as \'Название\'"})]
    [View("МодельL", new string[] {
            "Название as \'Название\'"})]
    public class Модель : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Модель CustomMembers)

        // *** End programmer edit section *** (Модель CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Модель.Название CustomAttributes)

        // *** End programmer edit section *** (Модель.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Модель.Название Get start)

                // *** End programmer edit section *** (Модель.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Модель.Название Get end)

                // *** End programmer edit section *** (Модель.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Модель.Название Set start)

                // *** End programmer edit section *** (Модель.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Модель.Название Set end)

                // *** End programmer edit section *** (Модель.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МодельE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МодельE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МодельE", typeof(IIS.Kursovaya.Модель));
                }
            }
            
            /// <summary>
            /// "МодельL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МодельL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МодельL", typeof(IIS.Kursovaya.Модель));
                }
            }
        }
    }
}
